  {
    codigo: "44905246",
    nome: "SEMOVENTES E EQUIPAMENTOS DE MONTARIA",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com animais para trabalho, produção, reprodução ou exposição e equipamentos de montaria, tais como: ANIMAIS NÃO DESTINADOS A LABORATÓRIO OU CORTE, ANIMAIS PARA JARDIM ZOOLÓGICO, ANIMAIS PARA PRODUÇÃO, REPRODUÇÃO E GUARDA, ANIMAIS PARA SELA E TRAÇÃO, SELAS E AFINS.",
    natureza: "449052",
    subitem: "46",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905247",
    nome: "EQUIPAMENTOS DE TIC - TELEFONIA",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com os seguintes equipamentos de TIC: CENTRAIS TELEFONICAS, EQUIPAMENTOS PARA VIDEO CONFERENCIA (TERMINAIS, CONVERSORES DE VIDEO, SOLUCOES DE STREAMING, CAMERAS PARA VIDEOCONFERENCIA), EXCETO QUANDO FOR AQUISICAO DE PECAS DESTINADAS A REPOSICAO DIRETAMENTE AO EQUIPAMENTO OU MESMO PARA ESTOQUE.",
    natureza: "449052",
    subitem: "47",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905248",
    nome: "VEÍCULOS DIVERSOS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com veículos não classificados em subitens específicos, tais como: EMPILHADEIRA, TRANSPALETE E AFINS.",
    natureza: "449052",
    subitem: "48",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905250",
    nome: "VEÍCULOS FERROVIÁRIOS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com veículos empregados em estradas de ferro, tais como: LOCOMOTIVA, PRANCHA, REBOQUE, TENDER, VAGÃO PARA TRANSPORTE DE CARGA OU PASSAGEIROS E AFINS.",
    natureza: "449052",
    subitem: "50",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905251",
    nome: "PEÇAS NÃO INCORPORÁVEIS A IMÓVEIS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com materiais empregados em imóveis e que possam ser removidos ou recuperados, avaliar valor unitário de pequeno vulto.",
    natureza: "449052",
    subitem: "51",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905252",
    nome: "VEÍCULOS DE TRAÇÃO MECÂNICA",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com veículos de tração mecânica, tais como: AUTOMÓVEL, AMBULANCIA, CAMINHAO, ONIBUS, MOTOCICLETA, CONSULTORIO VOLANTE E AFINS.",
    natureza: "449052",
    subitem: "52",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905253",
    nome: "CARROS DE COMBATE",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com veículos utilizados em manobras militares, tais como: AUTOCHOQUE, BLINDADO, CARRO-BOMBA, CARRO-TANQUE E AFINS.",
    natureza: "449052",
    subitem: "53",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905254",
    nome: "EQUIPAMENTOS, PEÇAS E ACESSÓRIOS AERONÁUTICOS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com equipamentos, peças e acessórios aeronáuticos, tais como: HÉLICE, MICROCOMPUTADOR DE BORDO, TURBINA E AFINS.",
    natureza: "449052",
    subitem: "54",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905256",
    nome: "EQUIPAMENTOS, PEÇAS E ACESSÓRIO DE PROTEÇÃO AO VOO",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com equipamentos, peças e acessórios de proteção ao vôo, tais como: RADAR, RÁDIO E AFINS.",
    natureza: "449052",
    subitem: "56",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905257",
    nome: "ACESSÓRIOS PARA VEÍCULOS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com acessórios para automóveis que possam ser DESINCORPORADOS, sem prejuízo dos mesmos, para aplicação em outro veículo, tais como: AR CONDICIONADO, CAPOTA E AFINS.",
    natureza: "449052",
    subitem: "57",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905258",
    nome: "EQUIPAMENTOS DE MERGULHO E SALVAMENTO",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com equipamentos destinados as atividades de mergulho e salvamento marítimo. ESCAFANDRO, JET-SKI, TANQUE DE OXIGÊNIO E AFINS.",
    natureza: "449052",
    subitem: "58",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905260",
    nome: "EQUIPAMENTOS, PEÇAS E ACESSÓRIOS MARÍTIMOS",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com equipamentos, peças e acessórios marítimos, tais como: INSTRUMENTOS DE NAVEGAÇÃO, INSTRUMENTOS DE MEDIÇÃO DO TEMPO, INSTRUMENTOS ÓTICOS, INSTRUMENTOS GEOGRÁFICOS E ASTRONÔMICOS, INSTRUMENTOS E APARELHOS METEOROLÓGICOS E AFINS.",
    natureza: "449052",
    subitem: "60",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905283",
    nome: "EQUIPAMENTOS E SISTEMA DE PROTEÇÃO E VIGILÂNCIA AMBIENTAL",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com equipamentos e sistema de proteção e vigilância ambiental.",
    natureza: "449052",
    subitem: "83",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
  {
    codigo: "44905289",
    nome: "EQUIPAMENTOS, SOBRESSALVENTES DE MÁQUINAS, MOTOR DE NAVIOS DE ESQUADRA",
    tipo: "Material permanente",
    descricao: "Registra o valor das despesas com componentes de propulsão de navios da esquadra e maquinarias de convés.",
    natureza: "449052",
    subitem: "89",
    fonte: "NO SEI nº 1/2024/DAI-EBSERH",
  },
];

